# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Story.destroy_all
Comment.destroy_all

user1 = User.create(name: 'RC', email: 'RC@edu.com', password_digest: '123', avatar: '123', bio: "social media apps are evil", img: Faker::Avatar.image )
user2 = User.create(name: 'Ali', email: 'Ali@edu.com', password_digest: '123', avatar: '123', bio: "I have super strength", img: Faker::Avatar.image)
user3 = User.create(name: 'Jamal', email: 'Jamal@edu.com', password_digest: '123', avatar: '123', bio: "FAAAAAXXXX Them", img: Faker::Avatar.image)
story1 = Story.create(title: 'Why did I pick this', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', author_id: user1.id)
story2 = Story.create(title: 'I hope this is working', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis ut diam quam nulla porttitor massa id. Enim tortor at auctor urna nunc id. Massa massa ultricies mi quis hendrerit dolor magna eget est. Et tortor consequat id porta nibh venenatis cras sed felis. Eu tincidunt tortor aliquam nulla. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Massa tincidunt dui ut ornare lectus sit amet est. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Pellentesque habitant morbi tristique senectus et netus et malesuada. Diam phasellus vestibulum lorem sed risus. Dictum varius duis at consectetur. In est ante in nibh.

Vulputate sapien nec sagittis aliquam malesuada bibendum. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Magna sit amet purus gravida quis blandit turpis. Morbi quis commodo odio aenean. Proin fermentum leo vel orci porta non pulvinar. Sed vulputate mi sit amet mauris commodo quis. Volutpat lacus laoreet non curabitur gravida arcu. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Mollis aliquam ut porttitor leo a. Elementum eu facilisis sed odio. Sed euismod nisi porta lorem mollis. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Varius quam quisque id diam vel quam elementum pulvinar etiam. Tristique et egestas quis ipsum suspendisse ultrices. Pharetra massa massa ultricies mi quis hendrerit dolor. Eu volutpat odio facilisis mauris sit amet.

Velit laoreet id donec ultrices tincidunt arcu non. Aliquam eleifend mi in nulla posuere sollicitudin aliquam. Quam id leo in vitae turpis. Consectetur a erat nam at lectus urna duis convallis convallis. Eu ultrices vitae auctor eu augue ut lectus arcu. Vestibulum lectus mauris ultrices eros. Non nisi est sit amet. Lacus luctus accumsan tortor posuere ac ut consequat semper. Urna porttitor rhoncus dolor purus non. Dapibus ultrices in iaculis nunc sed. Pulvinar mattis nunc sed blandit. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Viverra aliquet eget sit amet tellus. Eu consequat ac felis donec et odio. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Lacus luctus accumsan tortor posuere ac. Egestas integer eget aliquet nibh. Purus ut faucibus pulvinar elementum integer enim neque volutpat.

Faucibus ornare suspendisse sed nisi lacus. Sed ullamcorper morbi tincidunt ornare massa eget. Ultricies leo integer malesuada nunc vel. Pellentesque elit eget gravida cum. Neque egestas congue quisque egestas diam in arcu. Commodo quis imperdiet massa tincidunt nunc. Sit amet nisl purus in. Nunc sed augue lacus viverra vitae congue. Et pharetra pharetra massa massa ultricies. Pretium fusce id velit ut tortor. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Risus nec feugiat in fermentum. Felis donec et odio pellentesque diam volutpat commodo sed. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Sed felis eget velit aliquet sagittis id. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Morbi quis commodo odio aenean sed adipiscing diam donec.

Praesent semper feugiat nibh sed. Sed libero enim sed faucibus. Purus in massa tempor nec feugiat nisl. Magna sit amet purus gravida quis. Faucibus turpis in eu mi bibendum neque egestas congue. Aliquam malesuada bibendum arcu vitae elementum. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Elementum curabitur vitae nunc sed velit dignissim. Interdum velit euismod in pellentesque. Orci eu lobortis elementum nibh. Rhoncus est pellentesque elit ullamcorper. Dictum at tempor commodo ullamcorper a lacus vestibulum. Sit amet porttitor eget dolor morbi non arcu risus. Congue nisi vitae suscipit tellus mauris. Dictum non consectetur a erat nam at. Ultricies tristique nulla aliquet enim. Id porta nibh venenatis cras sed felis eget.

Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Libero id faucibus nisl tincidunt eget nullam non nisi. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Consectetur lorem donec massa sapien. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Nam libero justo laoreet sit amet cursus sit amet. Egestas erat imperdiet sed euismod nisi porta lorem mollis. At auctor urna nunc id cursus metus aliquam. Id consectetur purus ut faucibus pulvinar.

Neque vitae tempus quam pellentesque nec nam aliquam. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Vitae justo eget magna fermentum. Donec ac odio tempor orci dapibus. Sem et tortor consequat id porta. Senectus et netus et malesuada fames ac turpis. Suspendisse interdum consectetur libero id faucibus nisl. Quis commodo odio aenean sed. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor magna. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Vitae ultricies leo integer malesuada nunc vel risus. Ultrices dui sapien eget mi proin. Volutpat maecenas volutpat blandit aliquam. Quisque non tellus orci ac auctor. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Vulputate ut pharetra sit amet aliquam id diam. Pellentesque massa placerat duis ultricies. At in tellus integer feugiat scelerisque varius.

Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Lorem ipsum dolor sit amet consectetur. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Amet venenatis urna cursus eget. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Etiam sit amet nisl purus in mollis. Consequat nisl vel pretium lectus quam id. In dictum non consectetur a erat nam. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Cursus sit amet dictum sit. Urna porttitor rhoncus dolor purus non enim. Vitae sapien pellentesque habitant morbi tristique senectus. Magna eget est lorem ipsum dolor. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus.

Tellus cras adipiscing enim eu turpis egestas. Mauris sit amet massa vitae tortor condimentum lacinia quis. Sodales ut eu sem integer vitae justo eget magna fermentum. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. Et tortor consequat id porta nibh venenatis cras sed felis. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Egestas pretium aenean pharetra magna. Sed elementum tempus egestas sed sed. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a. Viverra orci sagittis eu volutpat. Lectus urna duis convallis convallis tellus id interdum velit. Luctus accumsan tortor posuere ac ut consequat semper viverra. Dolor purus non enim praesent elementum facilisis leo. Nunc non blandit massa enim nec dui nunc.

Consequat id porta nibh venenatis. Volutpat odio facilisis mauris sit. Nisl suscipit adipiscing bibendum est ultricies. Mattis enim ut tellus elementum sagittis. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus mauris. Mi quis hendrerit dolor magna eget est lorem ipsum. Penatibus et magnis dis parturient montes nascetur ridiculus. Dui faucibus in ornare quam viverra orci sagittis eu. Odio euismod lacinia at quis risus. Purus in mollis nunc sed id. Tincidunt lobortis feugiat vivamus at augue eget. In aliquam sem fringilla ut morbi tincidunt augue. Quis commodo odio aenean sed adipiscing diam donec adipiscing. Sollicitudin nibh sit amet commodo nulla facilisi. Auctor urna nunc id cursus metus aliquam eleifend.', author_id: user1.id)
story3 = Story.create(title: 'This is way more involved than I thought', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis ut diam quam nulla porttitor massa id. Enim tortor at auctor urna nunc id. Massa massa ultricies mi quis hendrerit dolor magna eget est. Et tortor consequat id porta nibh venenatis cras sed felis. Eu tincidunt tortor aliquam nulla. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Massa tincidunt dui ut ornare lectus sit amet est. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Pellentesque habitant morbi tristique senectus et netus et malesuada. Diam phasellus vestibulum lorem sed risus. Dictum varius duis at consectetur. In est ante in nibh.

Vulputate sapien nec sagittis aliquam malesuada bibendum. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Magna sit amet purus gravida quis blandit turpis. Morbi quis commodo odio aenean. Proin fermentum leo vel orci porta non pulvinar. Sed vulputate mi sit amet mauris commodo quis. Volutpat lacus laoreet non curabitur gravida arcu. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Mollis aliquam ut porttitor leo a. Elementum eu facilisis sed odio. Sed euismod nisi porta lorem mollis. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Varius quam quisque id diam vel quam elementum pulvinar etiam. Tristique et egestas quis ipsum suspendisse ultrices. Pharetra massa massa ultricies mi quis hendrerit dolor. Eu volutpat odio facilisis mauris sit amet.

Velit laoreet id donec ultrices tincidunt arcu non. Aliquam eleifend mi in nulla posuere sollicitudin aliquam. Quam id leo in vitae turpis. Consectetur a erat nam at lectus urna duis convallis convallis. Eu ultrices vitae auctor eu augue ut lectus arcu. Vestibulum lectus mauris ultrices eros. Non nisi est sit amet. Lacus luctus accumsan tortor posuere ac ut consequat semper. Urna porttitor rhoncus dolor purus non. Dapibus ultrices in iaculis nunc sed. Pulvinar mattis nunc sed blandit. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Viverra aliquet eget sit amet tellus. Eu consequat ac felis donec et odio. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Lacus luctus accumsan tortor posuere ac. Egestas integer eget aliquet nibh. Purus ut faucibus pulvinar elementum integer enim neque volutpat.

Faucibus ornare suspendisse sed nisi lacus. Sed ullamcorper morbi tincidunt ornare massa eget. Ultricies leo integer malesuada nunc vel. Pellentesque elit eget gravida cum. Neque egestas congue quisque egestas diam in arcu. Commodo quis imperdiet massa tincidunt nunc. Sit amet nisl purus in. Nunc sed augue lacus viverra vitae congue. Et pharetra pharetra massa massa ultricies. Pretium fusce id velit ut tortor. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Risus nec feugiat in fermentum. Felis donec et odio pellentesque diam volutpat commodo sed. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Sed felis eget velit aliquet sagittis id. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Morbi quis commodo odio aenean sed adipiscing diam donec.

Praesent semper feugiat nibh sed. Sed libero enim sed faucibus. Purus in massa tempor nec feugiat nisl. Magna sit amet purus gravida quis. Faucibus turpis in eu mi bibendum neque egestas congue. Aliquam malesuada bibendum arcu vitae elementum. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Elementum curabitur vitae nunc sed velit dignissim. Interdum velit euismod in pellentesque. Orci eu lobortis elementum nibh. Rhoncus est pellentesque elit ullamcorper. Dictum at tempor commodo ullamcorper a lacus vestibulum. Sit amet porttitor eget dolor morbi non arcu risus. Congue nisi vitae suscipit tellus mauris. Dictum non consectetur a erat nam at. Ultricies tristique nulla aliquet enim. Id porta nibh venenatis cras sed felis eget.

Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Libero id faucibus nisl tincidunt eget nullam non nisi. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Consectetur lorem donec massa sapien. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Nam libero justo laoreet sit amet cursus sit amet. Egestas erat imperdiet sed euismod nisi porta lorem mollis. At auctor urna nunc id cursus metus aliquam. Id consectetur purus ut faucibus pulvinar.

Neque vitae tempus quam pellentesque nec nam aliquam. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Vitae justo eget magna fermentum. Donec ac odio tempor orci dapibus. Sem et tortor consequat id porta. Senectus et netus et malesuada fames ac turpis. Suspendisse interdum consectetur libero id faucibus nisl. Quis commodo odio aenean sed. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor magna. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Vitae ultricies leo integer malesuada nunc vel risus. Ultrices dui sapien eget mi proin. Volutpat maecenas volutpat blandit aliquam. Quisque non tellus orci ac auctor. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Vulputate ut pharetra sit amet aliquam id diam. Pellentesque massa placerat duis ultricies. At in tellus integer feugiat scelerisque varius.

Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Lorem ipsum dolor sit amet consectetur. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Amet venenatis urna cursus eget. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Etiam sit amet nisl purus in mollis. Consequat nisl vel pretium lectus quam id. In dictum non consectetur a erat nam. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Cursus sit amet dictum sit. Urna porttitor rhoncus dolor purus non enim. Vitae sapien pellentesque habitant morbi tristique senectus. Magna eget est lorem ipsum dolor. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus.

Tellus cras adipiscing enim eu turpis egestas. Mauris sit amet massa vitae tortor condimentum lacinia quis. Sodales ut eu sem integer vitae justo eget magna fermentum. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. Et tortor consequat id porta nibh venenatis cras sed felis. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Egestas pretium aenean pharetra magna. Sed elementum tempus egestas sed sed. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a. Viverra orci sagittis eu volutpat. Lectus urna duis convallis convallis tellus id interdum velit. Luctus accumsan tortor posuere ac ut consequat semper viverra. Dolor purus non enim praesent elementum facilisis leo. Nunc non blandit massa enim nec dui nunc.

Consequat id porta nibh venenatis. Volutpat odio facilisis mauris sit. Nisl suscipit adipiscing bibendum est ultricies. Mattis enim ut tellus elementum sagittis. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus mauris. Mi quis hendrerit dolor magna eget est lorem ipsum. Penatibus et magnis dis parturient montes nascetur ridiculus. Dui faucibus in ornare quam viverra orci sagittis eu. Odio euismod lacinia at quis risus. Purus in mollis nunc sed id. Tincidunt lobortis feugiat vivamus at augue eget. In aliquam sem fringilla ut morbi tincidunt augue. Quis commodo odio aenean sed adipiscing diam donec adipiscing. Sollicitudin nibh sit amet commodo nulla facilisi. Auctor urna nunc id cursus metus aliquam eleifend.', author_id: user2.id)
story4 = Story.create(title: 'MOD 5 Advice: Avoid Creating Social Media Apps', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis ut diam quam nulla porttitor massa id. Enim tortor at auctor urna nunc id. Massa massa ultricies mi quis hendrerit dolor magna eget est. Et tortor consequat id porta nibh venenatis cras sed felis. Eu tincidunt tortor aliquam nulla. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Massa tincidunt dui ut ornare lectus sit amet est. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Pellentesque habitant morbi tristique senectus et netus et malesuada. Diam phasellus vestibulum lorem sed risus. Dictum varius duis at consectetur. In est ante in nibh.

Vulputate sapien nec sagittis aliquam malesuada bibendum. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Magna sit amet purus gravida quis blandit turpis. Morbi quis commodo odio aenean. Proin fermentum leo vel orci porta non pulvinar. Sed vulputate mi sit amet mauris commodo quis. Volutpat lacus laoreet non curabitur gravida arcu. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Mollis aliquam ut porttitor leo a. Elementum eu facilisis sed odio. Sed euismod nisi porta lorem mollis. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Varius quam quisque id diam vel quam elementum pulvinar etiam. Tristique et egestas quis ipsum suspendisse ultrices. Pharetra massa massa ultricies mi quis hendrerit dolor. Eu volutpat odio facilisis mauris sit amet.

Velit laoreet id donec ultrices tincidunt arcu non. Aliquam eleifend mi in nulla posuere sollicitudin aliquam. Quam id leo in vitae turpis. Consectetur a erat nam at lectus urna duis convallis convallis. Eu ultrices vitae auctor eu augue ut lectus arcu. Vestibulum lectus mauris ultrices eros. Non nisi est sit amet. Lacus luctus accumsan tortor posuere ac ut consequat semper. Urna porttitor rhoncus dolor purus non. Dapibus ultrices in iaculis nunc sed. Pulvinar mattis nunc sed blandit. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Viverra aliquet eget sit amet tellus. Eu consequat ac felis donec et odio. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Lacus luctus accumsan tortor posuere ac. Egestas integer eget aliquet nibh. Purus ut faucibus pulvinar elementum integer enim neque volutpat.

Faucibus ornare suspendisse sed nisi lacus. Sed ullamcorper morbi tincidunt ornare massa eget. Ultricies leo integer malesuada nunc vel. Pellentesque elit eget gravida cum. Neque egestas congue quisque egestas diam in arcu. Commodo quis imperdiet massa tincidunt nunc. Sit amet nisl purus in. Nunc sed augue lacus viverra vitae congue. Et pharetra pharetra massa massa ultricies. Pretium fusce id velit ut tortor. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Risus nec feugiat in fermentum. Felis donec et odio pellentesque diam volutpat commodo sed. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Sed felis eget velit aliquet sagittis id. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Morbi quis commodo odio aenean sed adipiscing diam donec.

Praesent semper feugiat nibh sed. Sed libero enim sed faucibus. Purus in massa tempor nec feugiat nisl. Magna sit amet purus gravida quis. Faucibus turpis in eu mi bibendum neque egestas congue. Aliquam malesuada bibendum arcu vitae elementum. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Elementum curabitur vitae nunc sed velit dignissim. Interdum velit euismod in pellentesque. Orci eu lobortis elementum nibh. Rhoncus est pellentesque elit ullamcorper. Dictum at tempor commodo ullamcorper a lacus vestibulum. Sit amet porttitor eget dolor morbi non arcu risus. Congue nisi vitae suscipit tellus mauris. Dictum non consectetur a erat nam at. Ultricies tristique nulla aliquet enim. Id porta nibh venenatis cras sed felis eget.

Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Libero id faucibus nisl tincidunt eget nullam non nisi. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Consectetur lorem donec massa sapien. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Nam libero justo laoreet sit amet cursus sit amet. Egestas erat imperdiet sed euismod nisi porta lorem mollis. At auctor urna nunc id cursus metus aliquam. Id consectetur purus ut faucibus pulvinar.

Neque vitae tempus quam pellentesque nec nam aliquam. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Vitae justo eget magna fermentum. Donec ac odio tempor orci dapibus. Sem et tortor consequat id porta. Senectus et netus et malesuada fames ac turpis. Suspendisse interdum consectetur libero id faucibus nisl. Quis commodo odio aenean sed. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor magna. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Vitae ultricies leo integer malesuada nunc vel risus. Ultrices dui sapien eget mi proin. Volutpat maecenas volutpat blandit aliquam. Quisque non tellus orci ac auctor. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Vulputate ut pharetra sit amet aliquam id diam. Pellentesque massa placerat duis ultricies. At in tellus integer feugiat scelerisque varius.

Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Lorem ipsum dolor sit amet consectetur. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Amet venenatis urna cursus eget. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Etiam sit amet nisl purus in mollis. Consequat nisl vel pretium lectus quam id. In dictum non consectetur a erat nam. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Cursus sit amet dictum sit. Urna porttitor rhoncus dolor purus non enim. Vitae sapien pellentesque habitant morbi tristique senectus. Magna eget est lorem ipsum dolor. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus.

Tellus cras adipiscing enim eu turpis egestas. Mauris sit amet massa vitae tortor condimentum lacinia quis. Sodales ut eu sem integer vitae justo eget magna fermentum. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. Et tortor consequat id porta nibh venenatis cras sed felis. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Egestas pretium aenean pharetra magna. Sed elementum tempus egestas sed sed. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a. Viverra orci sagittis eu volutpat. Lectus urna duis convallis convallis tellus id interdum velit. Luctus accumsan tortor posuere ac ut consequat semper viverra. Dolor purus non enim praesent elementum facilisis leo. Nunc non blandit massa enim nec dui nunc.

Consequat id porta nibh venenatis. Volutpat odio facilisis mauris sit. Nisl suscipit adipiscing bibendum est ultricies. Mattis enim ut tellus elementum sagittis. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus mauris. Mi quis hendrerit dolor magna eget est lorem ipsum. Penatibus et magnis dis parturient montes nascetur ridiculus. Dui faucibus in ornare quam viverra orci sagittis eu. Odio euismod lacinia at quis risus. Purus in mollis nunc sed id. Tincidunt lobortis feugiat vivamus at augue eget. In aliquam sem fringilla ut morbi tincidunt augue. Quis commodo odio aenean sed adipiscing diam donec adipiscing. Sollicitudin nibh sit amet commodo nulla facilisi. Auctor urna nunc id cursus metus aliquam eleifend.', author_id: user2.id)
story5 = Story.create(title: 'Signs of Grief', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis ut diam quam nulla porttitor massa id. Enim tortor at auctor urna nunc id. Massa massa ultricies mi quis hendrerit dolor magna eget est. Et tortor consequat id porta nibh venenatis cras sed felis. Eu tincidunt tortor aliquam nulla. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Massa tincidunt dui ut ornare lectus sit amet est. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Pellentesque habitant morbi tristique senectus et netus et malesuada. Diam phasellus vestibulum lorem sed risus. Dictum varius duis at consectetur. In est ante in nibh.

Vulputate sapien nec sagittis aliquam malesuada bibendum. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Magna sit amet purus gravida quis blandit turpis. Morbi quis commodo odio aenean. Proin fermentum leo vel orci porta non pulvinar. Sed vulputate mi sit amet mauris commodo quis. Volutpat lacus laoreet non curabitur gravida arcu. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Mollis aliquam ut porttitor leo a. Elementum eu facilisis sed odio. Sed euismod nisi porta lorem mollis. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Varius quam quisque id diam vel quam elementum pulvinar etiam. Tristique et egestas quis ipsum suspendisse ultrices. Pharetra massa massa ultricies mi quis hendrerit dolor. Eu volutpat odio facilisis mauris sit amet.

Velit laoreet id donec ultrices tincidunt arcu non. Aliquam eleifend mi in nulla posuere sollicitudin aliquam. Quam id leo in vitae turpis. Consectetur a erat nam at lectus urna duis convallis convallis. Eu ultrices vitae auctor eu augue ut lectus arcu. Vestibulum lectus mauris ultrices eros. Non nisi est sit amet. Lacus luctus accumsan tortor posuere ac ut consequat semper. Urna porttitor rhoncus dolor purus non. Dapibus ultrices in iaculis nunc sed. Pulvinar mattis nunc sed blandit. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Viverra aliquet eget sit amet tellus. Eu consequat ac felis donec et odio. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Lacus luctus accumsan tortor posuere ac. Egestas integer eget aliquet nibh. Purus ut faucibus pulvinar elementum integer enim neque volutpat.

Faucibus ornare suspendisse sed nisi lacus. Sed ullamcorper morbi tincidunt ornare massa eget. Ultricies leo integer malesuada nunc vel. Pellentesque elit eget gravida cum. Neque egestas congue quisque egestas diam in arcu. Commodo quis imperdiet massa tincidunt nunc. Sit amet nisl purus in. Nunc sed augue lacus viverra vitae congue. Et pharetra pharetra massa massa ultricies. Pretium fusce id velit ut tortor. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Risus nec feugiat in fermentum. Felis donec et odio pellentesque diam volutpat commodo sed. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Sed felis eget velit aliquet sagittis id. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Morbi quis commodo odio aenean sed adipiscing diam donec.

Praesent semper feugiat nibh sed. Sed libero enim sed faucibus. Purus in massa tempor nec feugiat nisl. Magna sit amet purus gravida quis. Faucibus turpis in eu mi bibendum neque egestas congue. Aliquam malesuada bibendum arcu vitae elementum. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Elementum curabitur vitae nunc sed velit dignissim. Interdum velit euismod in pellentesque. Orci eu lobortis elementum nibh. Rhoncus est pellentesque elit ullamcorper. Dictum at tempor commodo ullamcorper a lacus vestibulum. Sit amet porttitor eget dolor morbi non arcu risus. Congue nisi vitae suscipit tellus mauris. Dictum non consectetur a erat nam at. Ultricies tristique nulla aliquet enim. Id porta nibh venenatis cras sed felis eget.

Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Libero id faucibus nisl tincidunt eget nullam non nisi. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Consectetur lorem donec massa sapien. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Nam libero justo laoreet sit amet cursus sit amet. Egestas erat imperdiet sed euismod nisi porta lorem mollis. At auctor urna nunc id cursus metus aliquam. Id consectetur purus ut faucibus pulvinar.

Neque vitae tempus quam pellentesque nec nam aliquam. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Vitae justo eget magna fermentum. Donec ac odio tempor orci dapibus. Sem et tortor consequat id porta. Senectus et netus et malesuada fames ac turpis. Suspendisse interdum consectetur libero id faucibus nisl. Quis commodo odio aenean sed. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor magna. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Vitae ultricies leo integer malesuada nunc vel risus. Ultrices dui sapien eget mi proin. Volutpat maecenas volutpat blandit aliquam. Quisque non tellus orci ac auctor. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Vulputate ut pharetra sit amet aliquam id diam. Pellentesque massa placerat duis ultricies. At in tellus integer feugiat scelerisque varius.

Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Lorem ipsum dolor sit amet consectetur. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Amet venenatis urna cursus eget. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Etiam sit amet nisl purus in mollis. Consequat nisl vel pretium lectus quam id. In dictum non consectetur a erat nam. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Cursus sit amet dictum sit. Urna porttitor rhoncus dolor purus non enim. Vitae sapien pellentesque habitant morbi tristique senectus. Magna eget est lorem ipsum dolor. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus.

Tellus cras adipiscing enim eu turpis egestas. Mauris sit amet massa vitae tortor condimentum lacinia quis. Sodales ut eu sem integer vitae justo eget magna fermentum. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. Et tortor consequat id porta nibh venenatis cras sed felis. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Egestas pretium aenean pharetra magna. Sed elementum tempus egestas sed sed. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a. Viverra orci sagittis eu volutpat. Lectus urna duis convallis convallis tellus id interdum velit. Luctus accumsan tortor posuere ac ut consequat semper viverra. Dolor purus non enim praesent elementum facilisis leo. Nunc non blandit massa enim nec dui nunc.

Consequat id porta nibh venenatis. Volutpat odio facilisis mauris sit. Nisl suscipit adipiscing bibendum est ultricies. Mattis enim ut tellus elementum sagittis. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus mauris. Mi quis hendrerit dolor magna eget est lorem ipsum. Penatibus et magnis dis parturient montes nascetur ridiculus. Dui faucibus in ornare quam viverra orci sagittis eu. Odio euismod lacinia at quis risus. Purus in mollis nunc sed id. Tincidunt lobortis feugiat vivamus at augue eget. In aliquam sem fringilla ut morbi tincidunt augue. Quis commodo odio aenean sed adipiscing diam donec adipiscing. Sollicitudin nibh sit amet commodo nulla facilisi. Auctor urna nunc id cursus metus aliquam eleifend.', author_id: user2.id)
story6 = Story.create(title: 'I will help Reina with CSS', body: 'so her project will look nice', author_id: user3.id)
story7 = Story.create(title: 'Test2', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis ut diam quam nulla porttitor massa id. Enim tortor at auctor urna nunc id. Massa massa ultricies mi quis hendrerit dolor magna eget est. Et tortor consequat id porta nibh venenatis cras sed felis. Eu tincidunt tortor aliquam nulla. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Massa tincidunt dui ut ornare lectus sit amet est. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Pellentesque habitant morbi tristique senectus et netus et malesuada. Diam phasellus vestibulum lorem sed risus. Dictum varius duis at consectetur. In est ante in nibh.

Vulputate sapien nec sagittis aliquam malesuada bibendum. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Magna sit amet purus gravida quis blandit turpis. Morbi quis commodo odio aenean. Proin fermentum leo vel orci porta non pulvinar. Sed vulputate mi sit amet mauris commodo quis. Volutpat lacus laoreet non curabitur gravida arcu. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Mollis aliquam ut porttitor leo a. Elementum eu facilisis sed odio. Sed euismod nisi porta lorem mollis. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Varius quam quisque id diam vel quam elementum pulvinar etiam. Tristique et egestas quis ipsum suspendisse ultrices. Pharetra massa massa ultricies mi quis hendrerit dolor. Eu volutpat odio facilisis mauris sit amet.

Velit laoreet id donec ultrices tincidunt arcu non. Aliquam eleifend mi in nulla posuere sollicitudin aliquam. Quam id leo in vitae turpis. Consectetur a erat nam at lectus urna duis convallis convallis. Eu ultrices vitae auctor eu augue ut lectus arcu. Vestibulum lectus mauris ultrices eros. Non nisi est sit amet. Lacus luctus accumsan tortor posuere ac ut consequat semper. Urna porttitor rhoncus dolor purus non. Dapibus ultrices in iaculis nunc sed. Pulvinar mattis nunc sed blandit. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Viverra aliquet eget sit amet tellus. Eu consequat ac felis donec et odio. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Lacus luctus accumsan tortor posuere ac. Egestas integer eget aliquet nibh. Purus ut faucibus pulvinar elementum integer enim neque volutpat.

Faucibus ornare suspendisse sed nisi lacus. Sed ullamcorper morbi tincidunt ornare massa eget. Ultricies leo integer malesuada nunc vel. Pellentesque elit eget gravida cum. Neque egestas congue quisque egestas diam in arcu. Commodo quis imperdiet massa tincidunt nunc. Sit amet nisl purus in. Nunc sed augue lacus viverra vitae congue. Et pharetra pharetra massa massa ultricies. Pretium fusce id velit ut tortor. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Risus nec feugiat in fermentum. Felis donec et odio pellentesque diam volutpat commodo sed. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Sed felis eget velit aliquet sagittis id. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Morbi quis commodo odio aenean sed adipiscing diam donec.

Praesent semper feugiat nibh sed. Sed libero enim sed faucibus. Purus in massa tempor nec feugiat nisl. Magna sit amet purus gravida quis. Faucibus turpis in eu mi bibendum neque egestas congue. Aliquam malesuada bibendum arcu vitae elementum. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Elementum curabitur vitae nunc sed velit dignissim. Interdum velit euismod in pellentesque. Orci eu lobortis elementum nibh. Rhoncus est pellentesque elit ullamcorper. Dictum at tempor commodo ullamcorper a lacus vestibulum. Sit amet porttitor eget dolor morbi non arcu risus. Congue nisi vitae suscipit tellus mauris. Dictum non consectetur a erat nam at. Ultricies tristique nulla aliquet enim. Id porta nibh venenatis cras sed felis eget.

Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Libero id faucibus nisl tincidunt eget nullam non nisi. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Consectetur lorem donec massa sapien. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Nam libero justo laoreet sit amet cursus sit amet. Egestas erat imperdiet sed euismod nisi porta lorem mollis. At auctor urna nunc id cursus metus aliquam. Id consectetur purus ut faucibus pulvinar.

Neque vitae tempus quam pellentesque nec nam aliquam. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Vitae justo eget magna fermentum. Donec ac odio tempor orci dapibus. Sem et tortor consequat id porta. Senectus et netus et malesuada fames ac turpis. Suspendisse interdum consectetur libero id faucibus nisl. Quis commodo odio aenean sed. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor magna. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Vitae ultricies leo integer malesuada nunc vel risus. Ultrices dui sapien eget mi proin. Volutpat maecenas volutpat blandit aliquam. Quisque non tellus orci ac auctor. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Vulputate ut pharetra sit amet aliquam id diam. Pellentesque massa placerat duis ultricies. At in tellus integer feugiat scelerisque varius.

Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Lorem ipsum dolor sit amet consectetur. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Amet venenatis urna cursus eget. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Etiam sit amet nisl purus in mollis. Consequat nisl vel pretium lectus quam id. In dictum non consectetur a erat nam. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Cursus sit amet dictum sit. Urna porttitor rhoncus dolor purus non enim. Vitae sapien pellentesque habitant morbi tristique senectus. Magna eget est lorem ipsum dolor. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus.

Tellus cras adipiscing enim eu turpis egestas. Mauris sit amet massa vitae tortor condimentum lacinia quis. Sodales ut eu sem integer vitae justo eget magna fermentum. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. Et tortor consequat id porta nibh venenatis cras sed felis. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Egestas pretium aenean pharetra magna. Sed elementum tempus egestas sed sed. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a. Viverra orci sagittis eu volutpat. Lectus urna duis convallis convallis tellus id interdum velit. Luctus accumsan tortor posuere ac ut consequat semper viverra. Dolor purus non enim praesent elementum facilisis leo. Nunc non blandit massa enim nec dui nunc.

Consequat id porta nibh venenatis. Volutpat odio facilisis mauris sit. Nisl suscipit adipiscing bibendum est ultricies. Mattis enim ut tellus elementum sagittis. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus mauris. Mi quis hendrerit dolor magna eget est lorem ipsum. Penatibus et magnis dis parturient montes nascetur ridiculus. Dui faucibus in ornare quam viverra orci sagittis eu. Odio euismod lacinia at quis risus. Purus in mollis nunc sed id. Tincidunt lobortis feugiat vivamus at augue eget. In aliquam sem fringilla ut morbi tincidunt augue. Quis commodo odio aenean sed adipiscing diam donec adipiscing. Sollicitudin nibh sit amet commodo nulla facilisi. Auctor urna nunc id cursus metus aliquam eleifend.', author_id: user3.id)
story8 = Story.create(title: 'Test3', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis ut diam quam nulla porttitor massa id. Enim tortor at auctor urna nunc id. Massa massa ultricies mi quis hendrerit dolor magna eget est. Et tortor consequat id porta nibh venenatis cras sed felis. Eu tincidunt tortor aliquam nulla. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Massa tincidunt dui ut ornare lectus sit amet est. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Pellentesque habitant morbi tristique senectus et netus et malesuada. Diam phasellus vestibulum lorem sed risus. Dictum varius duis at consectetur. In est ante in nibh.

Vulputate sapien nec sagittis aliquam malesuada bibendum. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Magna sit amet purus gravida quis blandit turpis. Morbi quis commodo odio aenean. Proin fermentum leo vel orci porta non pulvinar. Sed vulputate mi sit amet mauris commodo quis. Volutpat lacus laoreet non curabitur gravida arcu. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Mollis aliquam ut porttitor leo a. Elementum eu facilisis sed odio. Sed euismod nisi porta lorem mollis. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Varius quam quisque id diam vel quam elementum pulvinar etiam. Tristique et egestas quis ipsum suspendisse ultrices. Pharetra massa massa ultricies mi quis hendrerit dolor. Eu volutpat odio facilisis mauris sit amet.

Velit laoreet id donec ultrices tincidunt arcu non. Aliquam eleifend mi in nulla posuere sollicitudin aliquam. Quam id leo in vitae turpis. Consectetur a erat nam at lectus urna duis convallis convallis. Eu ultrices vitae auctor eu augue ut lectus arcu. Vestibulum lectus mauris ultrices eros. Non nisi est sit amet. Lacus luctus accumsan tortor posuere ac ut consequat semper. Urna porttitor rhoncus dolor purus non. Dapibus ultrices in iaculis nunc sed. Pulvinar mattis nunc sed blandit. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Viverra aliquet eget sit amet tellus. Eu consequat ac felis donec et odio. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Lacus luctus accumsan tortor posuere ac. Egestas integer eget aliquet nibh. Purus ut faucibus pulvinar elementum integer enim neque volutpat.

Faucibus ornare suspendisse sed nisi lacus. Sed ullamcorper morbi tincidunt ornare massa eget. Ultricies leo integer malesuada nunc vel. Pellentesque elit eget gravida cum. Neque egestas congue quisque egestas diam in arcu. Commodo quis imperdiet massa tincidunt nunc. Sit amet nisl purus in. Nunc sed augue lacus viverra vitae congue. Et pharetra pharetra massa massa ultricies. Pretium fusce id velit ut tortor. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Risus nec feugiat in fermentum. Felis donec et odio pellentesque diam volutpat commodo sed. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Sed felis eget velit aliquet sagittis id. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Morbi quis commodo odio aenean sed adipiscing diam donec.

Praesent semper feugiat nibh sed. Sed libero enim sed faucibus. Purus in massa tempor nec feugiat nisl. Magna sit amet purus gravida quis. Faucibus turpis in eu mi bibendum neque egestas congue. Aliquam malesuada bibendum arcu vitae elementum. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Elementum curabitur vitae nunc sed velit dignissim. Interdum velit euismod in pellentesque. Orci eu lobortis elementum nibh. Rhoncus est pellentesque elit ullamcorper. Dictum at tempor commodo ullamcorper a lacus vestibulum. Sit amet porttitor eget dolor morbi non arcu risus. Congue nisi vitae suscipit tellus mauris. Dictum non consectetur a erat nam at. Ultricies tristique nulla aliquet enim. Id porta nibh venenatis cras sed felis eget.

Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Libero id faucibus nisl tincidunt eget nullam non nisi. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Consectetur lorem donec massa sapien. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Nam libero justo laoreet sit amet cursus sit amet. Egestas erat imperdiet sed euismod nisi porta lorem mollis. At auctor urna nunc id cursus metus aliquam. Id consectetur purus ut faucibus pulvinar.

Neque vitae tempus quam pellentesque nec nam aliquam. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Vitae justo eget magna fermentum. Donec ac odio tempor orci dapibus. Sem et tortor consequat id porta. Senectus et netus et malesuada fames ac turpis. Suspendisse interdum consectetur libero id faucibus nisl. Quis commodo odio aenean sed. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor magna. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Vitae ultricies leo integer malesuada nunc vel risus. Ultrices dui sapien eget mi proin. Volutpat maecenas volutpat blandit aliquam. Quisque non tellus orci ac auctor. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Vulputate ut pharetra sit amet aliquam id diam. Pellentesque massa placerat duis ultricies. At in tellus integer feugiat scelerisque varius.

Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Lorem ipsum dolor sit amet consectetur. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Amet venenatis urna cursus eget. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Etiam sit amet nisl purus in mollis. Consequat nisl vel pretium lectus quam id. In dictum non consectetur a erat nam. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Cursus sit amet dictum sit. Urna porttitor rhoncus dolor purus non enim. Vitae sapien pellentesque habitant morbi tristique senectus. Magna eget est lorem ipsum dolor. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus.

Tellus cras adipiscing enim eu turpis egestas. Mauris sit amet massa vitae tortor condimentum lacinia quis. Sodales ut eu sem integer vitae justo eget magna fermentum. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. Et tortor consequat id porta nibh venenatis cras sed felis. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Egestas pretium aenean pharetra magna. Sed elementum tempus egestas sed sed. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a. Viverra orci sagittis eu volutpat. Lectus urna duis convallis convallis tellus id interdum velit. Luctus accumsan tortor posuere ac ut consequat semper viverra. Dolor purus non enim praesent elementum facilisis leo. Nunc non blandit massa enim nec dui nunc.

Consequat id porta nibh venenatis. Volutpat odio facilisis mauris sit. Nisl suscipit adipiscing bibendum est ultricies. Mattis enim ut tellus elementum sagittis. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus mauris. Mi quis hendrerit dolor magna eget est lorem ipsum. Penatibus et magnis dis parturient montes nascetur ridiculus. Dui faucibus in ornare quam viverra orci sagittis eu. Odio euismod lacinia at quis risus. Purus in mollis nunc sed id. Tincidunt lobortis feugiat vivamus at augue eget. In aliquam sem fringilla ut morbi tincidunt augue. Quis commodo odio aenean sed adipiscing diam donec adipiscing. Sollicitudin nibh sit amet commodo nulla facilisi. Auctor urna nunc id cursus metus aliquam eleifend.', author_id: user3.id)
comment1 = Comment.create(body: 'Test0', author_id: user1.id, story_id: story1.id)
comment2 = Comment.create(body: 'Test1', author_id: user1.id, story_id: story1.id)
comment3 = Comment.create(body: 'Test2', author_id: user1.id, story_id: story1.id)

puts 'seeded'